name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1 # Cambia a tu región de AWS

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create environment file
      run: |
        cat << EOF > .env.local
        NEXT_PUBLIC_STRAPI_URL=${{ secrets.NEXT_PUBLIC_STRAPI_URL }}
        STRAPI_TOKEN=${{ secrets.STRAPI_TOKEN }}
        NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
        EOF

    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_STRAPI_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_URL }}
        STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
        NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to S3
      run: |
        aws s3 sync ./out s3://${{ secrets.S3_BUCKET_NAME }} --delete --cache-control "max-age=31536000,public"
        aws s3 cp ./out s3://${{ secrets.S3_BUCKET_NAME }} --recursive --exclude "*" --include "*.html" --cache-control "no-cache,no-store,must-revalidate"
        aws s3 cp ./out s3://${{ secrets.S3_BUCKET_NAME }} --recursive --exclude "*" --include "*.js" --include "*.css" --cache-control "max-age=31536000,public"

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"

    - name: Deploy success notification
      if: success()
      run: |
        echo "🚀 Deployment successful!"
        echo "🌐 Site deployed to: ${{ secrets.SITE_URL }}"
