name: Build and Validate for Vercel Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-validate:
    name: Build and Validate Next.js Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify Node.js and npm versions
      run: |
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "Next.js version: $(npm list next)"
      
    - name: Build application
      run: npm run build
        
    - name: Build success
      run: echo "✅ Build and validation completed successfully! Vercel will auto-deploy from GitHub."
